apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
      - name: db
        image: "postgres:12"
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command: [ "/bin/sh", "-c", "pg_isready -h 127.0.0.1 -p 5432" ]
          initialDelaySeconds: 10
          periodSeconds: 30
        env:
        - name: POSTGRES_USER
          value: polls
        - name: POSTGRES_PASSWORD
          value: polls
        - name: POSTGRES_DB
          value: polls
      resources:
        limits:
          cpu: 500m
        requests:
          cpu: 200m
          memory: 500Mi
