apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: preview-map
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        service: preview-map
    spec:
      containers:
      - name: preview-map
        resources:
          limits:
            cpu: 250m
          requests:
            cpu: 50m
            memory: 200Mi
          
        env:
        - name: NODE_ENV
          value: production
        image: "gcr.io/magda-221800/magda-preview-map:0.0.50-0"
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 0
