apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: calculator
    spec:
      containers:
      # The image isn't actually used since it's overriden in the Calculator's
      # Sync Configuration.
      - image: alpine
        name: calculator
