apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
      role: data
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - elasticsearch
                - key: role
                  operator: In
                  values:
                  - data
              topologyKey: kubernetes.io/hostname
      containers:
      - name: elasticsearch
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: "gcr.io/magda-221800/magda-elasticsearch:0.0.50-3"
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
            memory: 1000Mi
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: NODE_DATA
          value: "true"
        - name: NODE_MASTER
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        - name: NODE_INGEST
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: ES_PLUGINS_INSTALL
          value: ""
        - name: NETWORK_HOST
          value: "0.0.0.0"
        - name: HTTP_ENABLE
          value: "true"
        - name: REPO
          value: /snapshots
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
      initContainers:
      - name: set-limits
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
        - "sh"
        - "-c"
        - "sysctl -w vm.max_map_count=262144 && ulimit -l unlimited"
      terminationGracePeriodSeconds: 0
